# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditPost():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editPost(self):
    self.driver.get("https://conf.7ya.ru/")
    self.driver.set_window_size(965, 1093)
    self.driver.find_element(By.ID, "btnlgntop").click()
    self.driver.find_element(By.LINK_TEXT, "Мои опросы").click()
    self.driver.find_element(By.CSS_SELECTOR, "td > a:nth-child(1) > img").click()
    self.driver.find_element(By.ID, "ctl00_main_ddlVisVoting").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ctl00_main_ddlVisVoting > option:nth-child(3)").click()
    self.driver.find_element(By.ID, "ctl00_main_dllVisResult").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ctl00_main_dllVisResult > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "ctl00_main_sendform1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".initial").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-nav").click()
    self.driver.find_element(By.LINK_TEXT, "Мои опросы").click()
  
